# Generated by Django 4.0.4 on 2023-03-12 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_names', models.BooleanField()),
                ('player_name', models.BooleanField()),
                ('alliance_name', models.BooleanField()),
                ('auto_relogin', models.IntegerField()),
                ('player_id', models.IntegerField(default=None)),
                ('world_id', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AutoBuildSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autostart', models.BooleanField()),
                ('enable_building', models.BooleanField()),
                ('enable_units', models.BooleanField()),
                ('enable_ships', models.BooleanField()),
                ('timeinterval', models.IntegerField()),
                ('instant_buy', models.BooleanField()),
                ('player_id', models.IntegerField()),
                ('world_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AutoCultureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autostart', models.BooleanField()),
                ('player_id', models.IntegerField(default=None)),
                ('world_id', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AutoCultureTownSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.BooleanField()),
                ('triumph', models.BooleanField()),
                ('theater', models.BooleanField()),
                ('player_id', models.IntegerField(default=None, null=True)),
                ('town_id', models.IntegerField(default=None)),
                ('world_id', models.CharField(default=None, max_length=30, null=True)),
                ('auto_culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_settings', to='bot_queues.autoculturesettings')),
            ],
        ),
        migrations.CreateModel(
            name='AutoFarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autostart', models.BooleanField()),
                ('method', models.IntegerField()),
                ('timebetween', models.IntegerField()),
                ('skipwhenfull', models.BooleanField()),
                ('lowresfirst', models.BooleanField()),
                ('stoplootbelow', models.BooleanField()),
                ('player_id', models.IntegerField(default=None)),
                ('world_id', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_lang', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=100)),
                ('world_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('premium_grepolis', models.BooleanField(default=False)),
                ('premium_time', models.IntegerField(blank=True, default=1679263671.0, null=True)),
                ('trial_time', models.IntegerField(blank=True, null=True)),
                ('facebook_like', models.IntegerField(blank=True, null=True)),
                ('assistant_settings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_queues.assistantsettings')),
                ('autobuild_settings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_queues.autobuildsettings')),
                ('autoculture_settings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoculture_settings', to='bot_queues.autoculturesettings')),
                ('autofarm_settings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_queues.autofarmsettings')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('world_id', models.CharField(default=0, max_length=20)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 12, 22, 7, 51, 580376, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('world_id', models.CharField(default=0, max_length=20)),
                ('player_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField()),
                ('auto_culture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.autoculturetownsettings')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='bot_queues.playerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=1)),
                ('world_id', models.CharField(default=1, max_length=20)),
                ('town_id', models.IntegerField(default=1)),
                ('item_name', models.CharField(default='building', max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('added', models.DateTimeField(default=datetime.datetime(2023, 3, 12, 22, 7, 51, 579555, tzinfo=utc))),
                ('town_obj', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_orders', to='bot_queues.town')),
            ],
        ),
        migrations.CreateModel(
            name='ShipOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=1)),
                ('world_id', models.CharField(default=1, max_length=20)),
                ('town_id', models.IntegerField(default=1)),
                ('item_name', models.CharField(default='building', max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('added', models.DateTimeField(default=datetime.datetime(2023, 3, 12, 22, 7, 51, 580002, tzinfo=utc))),
                ('town_obj', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_orders', to='bot_queues.town')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('world_id', models.CharField(max_length=20)),
                ('town_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('added', models.DateTimeField(default=datetime.datetime(2023, 3, 12, 22, 7, 51, 579175, tzinfo=utc))),
                ('town_obj', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_orders', to='bot_queues.town')),
            ],
        ),
    ]
