# Generated by Django 4.0.4 on 2023-03-06 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoculturetownsettings',
            name='player_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='autoculturetownsettings',
            name='town_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='autoculturetownsettings',
            name='world_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 11, 50, 24, 606850)),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='assistant_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_queues.assistantsettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='autobuild_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_queues.autobuildsettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='autoculture_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoculture_settings', to='bot_queues.autoculturesettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='autofarm_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_queues.autofarmsettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='premium_time',
            field=models.IntegerField(blank=True, default=1678719024.0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 11, 50, 24, 606850)),
        ),
        migrations.AlterField(
            model_name='shiporder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 11, 50, 24, 606850)),
        ),
        migrations.AlterField(
            model_name='unitorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 11, 50, 24, 606850)),
        ),
    ]
