# Generated by Django 4.0.8 on 2023-02-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='AssistantSettings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.assistantsettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='AutoBuildSettings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.autobuildsettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='AutoCultureSettings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.autoculturesettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='AutoFarmSettings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.autofarmsettings'),
        ),
    ]
