# Generated by Django 4.0.4 on 2023-03-05 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 15, 30, 4, 253140)),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='premium_time',
            field=models.IntegerField(blank=True, default=1678635004.0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 15, 30, 4, 254314)),
        ),
        migrations.AlterField(
            model_name='shiporder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 15, 30, 4, 253957)),
        ),
        migrations.AlterField(
            model_name='unitorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 15, 30, 4, 253549)),
        ),
    ]
