# Generated by Django 4.0.4 on 2023-02-10 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobuildsettings',
            name='player_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='autobuildsettings',
            name='world_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 9, 55, 43, 761531)),
        ),
    ]
