# Generated by Django 4.0.8 on 2023-02-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0002_alter_playerinfo_autoculture_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='facebook_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='premium_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='trial_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
