# Generated by Django 4.0.8 on 2023-02-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0002_alter_playerinfo_assistantsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autobuildsettings',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='autofarmsettings',
            name='player_id',
        ),
    ]
