# Generated by Django 4.0.8 on 2023-02-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0003_alter_playerinfo_facebook_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='assistant_settings',
            field=models.OneToOneField(blank=True, default={}, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.assistantsettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='autobuild_settings',
            field=models.OneToOneField(blank=True, default={}, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.autobuildsettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='autoculture_settings',
            field=models.OneToOneField(blank=True, default={}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoculture_settings', to='bot_queues.autoculturesettings'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='autofarm_settings',
            field=models.OneToOneField(blank=True, default={}, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_queues.autofarmsettings'),
        ),
    ]
