# Generated by Django 4.0.4 on 2023-02-10 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0003_alter_autobuildsettings_player_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autobuildsettings',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='autobuildsettings',
            name='world_id',
        ),
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 9, 59, 31, 498663)),
        ),
    ]
