# Generated by Django 4.0.4 on 2023-03-06 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0003_alter_autoculturetownsettings_town_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 11, 58, 0, 446451)),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='premium_time',
            field=models.IntegerField(blank=True, default=1678719480.0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 11, 58, 0, 446451)),
        ),
        migrations.AlterField(
            model_name='shiporder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 11, 58, 0, 446451)),
        ),
        migrations.AlterField(
            model_name='unitorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 11, 58, 0, 446451)),
        ),
    ]
