# Generated by Django 4.0.4 on 2023-02-10 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0004_remove_autobuildsettings_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobuildsettings',
            name='player_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='autobuildsettings',
            name='world_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 9, 59, 41, 550251)),
        ),
    ]
