# Generated by Django 4.0.4 on 2023-03-07 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0004_alter_buildingorder_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 11, 17, 35, 162398)),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='premium_time',
            field=models.IntegerField(blank=True, default=1678803455.0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 11, 17, 35, 162398)),
        ),
        migrations.AlterField(
            model_name='shiporder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 11, 17, 35, 162398)),
        ),
        migrations.AlterField(
            model_name='unitorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 11, 17, 35, 162398)),
        ),
    ]
