# Generated by Django 4.0.4 on 2023-02-10 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0005_autobuildsettings_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobuildsettings',
            name='player_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='autobuildsettings',
            name='world_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 10, 6, 11, 964535)),
        ),
    ]
