# Generated by Django 4.0.4 on 2023-02-10 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0006_alter_autobuildsettings_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 10, 12, 43, 337786)),
        ),
    ]
