# Generated by Django 4.0.4 on 2023-02-10 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0011_autoculturesettings_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoculturetownsettings',
            name='player_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='autoculturetownsettings',
            name='town_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='autoculturetownsettings',
            name='world_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 10, 30, 49, 843624)),
        ),
    ]
