# Generated by Django 4.1.7 on 2023-02-27 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0012_autoculturetownsettings_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 23, 55, 23, 218395)),
        ),
    ]
