# Generated by Django 4.1.7 on 2023-02-27 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_queues', '0013_alter_buildingorder_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingorder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 23, 56, 0, 22210)),
        ),
    ]
